services:
  postgres_auth:
    image: postgres:15
    container_name: postgres_auth
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 17052007
    ports:
      - "5433:5432"
    networks:
      - auth_network
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data

  auth_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: innouserservice-auth_service-1
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_auth:5432/auth_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 17052007
      SERVER_PORT: 8081
      JWT_SECRET: MySuperSecretKeyForJWTMySuperSecretKeyForJWT
      JWT_EXPIRATION: 3600000
      JWT_HEADER: Authorization
      JWT_TOKEN_PREFIX: Bearer
      JWT_ROLE_PREFIX: ROLE_
      PASSWORD_STRENGTH: 16
      PASSWORD_HASH_ALGORITHM: SHA-256
      PASSWORD_SALT_ALGORITHM: SHA1PRNG
      PASSWORD_SALT_LENGTH: 16
    depends_on:
      - postgres_auth
    ports:
      - "8081:8081"
    networks:
      - auth_network

networks:
  auth_network:

volumes:
  postgres_auth_data:
