version: "3.9"

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth_service
    env_file: .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "${SERVER_PORT}:8081"
    depends_on:
      postgres_auth:
        condition: service_healthy
    networks:
      - innoauthservice_network

  postgres_auth:
    image: postgres:15
    container_name: postgres_auth_service
    env_file: .env
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    networks:
      - innoauthservice_network

volumes:
  postgres_auth_data:

networks:
  innoauthservice_network:
    driver: bridge
