package com.innowise.userservice.model.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Column;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.GenerationType;
import lombok.Data;

import java.time.LocalDate;

/**
 * Entity representing a payment card associated with a user.
 * <p>
 * Each {@link CardInfo} belongs to a single {@link User}.
 * The relationship is many-to-one and uses lazy loading.
 * </p>
 */
@Entity
@Table(name = "card_info")
@Data
public class CardInfo {

    /**
     * Primary key of the card.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The user who owns this card.
     * Cannot be null.
     * Uses lazy fetching to improve performance.
     */
    @ManyToOne
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * The card number.
     * Cannot be null.
     */
    @Column(name = "number", nullable = false)
    private String number;

    /**
     * Name of the cardholder.
     * Cannot be null.
     */
    @Column(name = "holder", nullable = false)
    private String holder;

    /**
     * Expiration date of the card.
     * Cannot be null.
     */
    @Column(name = "expiration_date", nullable = false)
    private LocalDate expirationDate;
}
