server:
  port: ${SERVER_PORT:8081}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/auth_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:17052007}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml

jwt:
  secret: ${JWT_SECRET:MySuperSecretKeyForJWTMySuperSecretKeyForJWT}
  expiration: ${JWT_EXPIRATION:3600000}
  header: ${JWT_HEADER:Authorization}
  token:
    prefix: ${JWT_TOKEN_PREFIX:Bearer}
  role:
    prefix: ${JWT_ROLE_PREFIX:ROLE_}

password:
  strength: ${PASSWORD_STRENGTH:16}
  hash:
    algorithm: ${PASSWORD_HASH_ALGORITHM:SHA-256}
  salt:
    algorithm: ${PASSWORD_SALT_ALGORITHM:SHA1PRNG}
    length: ${PASSWORD_SALT_LENGTH:16}
