spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/OrderService
    username: postgres
    password: 17052007

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml


