spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET:MySuperSecretKeyForJWTMySuperSecretKeyForJWT}
  expiration: ${JWT_EXPIRATION:3600000}
  header: ${JWT_HEADER:Authorization}
  tokenPrefix: ${JWT_TOKEN_PREFIX:Bearer}
  rolePrefix: ${JWT_ROLE_PREFIX:ROLE_}

password:
  strength: ${PASSWORD_STRENGTH:16}
  hash-algorithm: ${PASSWORD_HASH_ALGORITHM:SHA-256}
  salt-algorithm: ${PASSWORD_SALT_ALGORITHM:SHA1PRNG}
  salt-length: ${PASSWORD_SALT_LENGTH:16}

server:
  port: ${SERVER_PORT:8081}
