spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ord_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:17052007}

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml

server:
  port: ${SERVER_PORT:8083}

user:
  service:
    url: http://localhost:8081
