server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/UserService
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    enabled: true
    contexts: dev

  data:
    redis:
     host: localhost
     port: 6379
  cache:
     type: redis
