spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/UserService
    username: postgres
    password: 17052007
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true

  server:
    port: 8080

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
