package server.data.entity;

import jakarta.persistence.*;
import lombok.Data;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

/**
 * Entity representing a user in the system.
 * <p>
 * Each user can have multiple associated {@link CardInfo} objects.
 * Cascade operations are enabled so that changes to a user automatically propagate to their cards.
 * </p>
 */
@Entity
@Data
@Table(name = "users")  // escape with quotes for H2
public class User {

    /**
     * Primary key of the user.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * First name of the user.
     * Cannot be null.
     */
    @Column(nullable = false)
    private String name;

    /**
     * Last name of the user.
     * Cannot be null.
     */
    @Column(nullable = false)
    private String surname;

    /**
     * Birthdate of the user.
     * Cannot be null.
     */
    @Column(nullable = false)
    private LocalDate birthDate;

    /**
     * Email of the user.
     * Must be unique and cannot be null.
     */
    @Column(nullable = false, unique = true)
    private String email;

    /**
     * List of cards associated with this user.
     * Cascade operations ensure that updates/deletes propagate.
     */
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<CardInfo> cards = new ArrayList<>();

}
