package com.innowise.userservice.data.entity;

import jakarta.persistence.*;
import lombok.Data;

import java.time.LocalDate;

/**
 * Entity representing a payment card associated with a user.
 * <p>
 * Each {@link CardInfo} belongs to a single {@link User}.
 * The relationship is many-to-one and uses lazy loading.
 * </p>
 */
@Entity
@Table(name = "card_info")
@Data
public class CardInfo {

    /**
     * Primary key of the card.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The user who owns this card.
     * Cannot be null.
     * Uses lazy fetching to improve performance.
     */
    @ManyToOne
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * The card number.
     * Cannot be null.
     */
    @Column(nullable = false)
    private String cardNumber;

    /**
     * Name of the cardholder.
     * Cannot be null.
     */
    @Column(nullable = false)
    private String cardHolder;

    /**
     * Expiration date of the card.
     * Cannot be null.
     */
    @Column(nullable = false)
    private LocalDate cardExpiryDate;
}
